#pragma once

enum class ERROR_CODE : unsigned short
{
	NONE = 0,

	USER_MGR_INVALID_USER_INDEX = 11,
	USER_MGR_INVALID_USER_UNIQUEID = 12,

	LOGIN_USER_ALREADY = 31,
	LOGIN_USER_USED_ALL_OBJ = 32,
	LOGIN_USER_INVALID_PW = 33,

	NEW_GROUND_USED_ALL_OBJ = 41,
	NEW_GROUND_FAIL_ENTER = 42,

	ENTER_GROUND_NOT_FINDE_USER = 51,
	ENTER_GROUND_INVALID_USER_STATUS = 52,
	ENTER_GROUND_NOT_USED_STATUS = 53,
	ENTER_GROUND_FULL_USER = 54,

	GROUND_INVALID_INDEX = 61,
	GROUND_NOT_USED = 62,
	GROUND_TOO_MANY_PACKET = 63,

	LEAVE_GROUND_INVALID_GROUND_INDEX = 71,

	CHAT_GROUND_INVALID_GROUND_NUMBER = 81,
};